on: push
jobs:
    build-node:
        name: Build and run node project
        runs-on: ubuntu-latest
        container: node:24
        steps:
            - uses: actions/checkout@v5
            - run: npm install
#            - run: node app.js
